FROM registry.access.redhat.com/ubi8
RUN apt-cache update && apt-get install php php-pdo php-zip php-json git-core
RUN apt-get install php-xml php-mbstring
RUN git clone https://github.com/Kamalisk/arkhamdb
RUN git clone https://github.com/Kamalisk/arkhamdb-json-data
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && php composer-setup.php --install-dir=/usr/local/bin --filename=composer --1 && rm composer-setup.php
RUN cd arkhamdb && composer update && composer install
 

